-- Supabase Database Schema
-- Auto-generated by Cozanet OS

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Item table
CREATE TABLE IF NOT EXISTS item (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS policies
ALTER TABLE item ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can read item" ON item FOR SELECT USING (true);
CREATE POLICY "Users can insert item" ON item FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can update item" ON item FOR UPDATE USING (true);
CREATE POLICY "Users can delete item" ON item FOR DELETE USING (true);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_item_updated_at BEFORE UPDATE ON item FOR EACH ROW EXECUTE FUNCTION update_updated_at();
