/** Auth API Route — Auto-generated by Cozanet OS. Uses bcrypt + Supabase. */
import { NextRequest, NextResponse } from 'next/server';
import bcrypt from 'bcryptjs';
export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

export async function POST(req: NextRequest) {
  const body = await req.json();
  const { action, email, password } = body;
  if (!email || !password) return NextResponse.json({ error: "Email and password required" }, { status: 400 });

  if (action === "register") {
    const hashedPassword = await bcrypt.hash(password, 10);
    const resp = await fetch(`${SUPABASE_URL}/rest/v1/users`, {
      method: 'POST',
      headers: {
        'apikey': SUPABASE_KEY!,
        'Authorization': `Bearer ${SUPABASE_KEY}`,
        'Content-Type': 'application/json',
        'Prefer': 'return=representation',
      },
      body: JSON.stringify({ email, password_hash: hashedPassword, created_at: new Date().toISOString() }),
    });
    if (!resp.ok) {
      const err = await resp.text();
      if (err.includes("duplicate")) return NextResponse.json({ error: "User already exists" }, { status: 409 });
      return NextResponse.json({ error: "Registration failed" }, { status: 500 });
    }
    const user = await resp.json();
    const token = crypto.randomUUID();
    return NextResponse.json({ success: true, token, email, userId: user[0]?.id });
  }

  if (action === "login") {
    const resp = await fetch(SUPABASE_URL + "/rest/v1/users?email=eq." + encodeURIComponent(email) + "&select=*", {
      headers: {
        'apikey': SUPABASE_KEY!,
        'Authorization': `Bearer ${SUPABASE_KEY}`,
      },
    });
    const users = await resp.json();
    if (!users.length) return NextResponse.json({ error: "Invalid credentials" }, { status: 401 });
    const user = users[0];
    const valid = await bcrypt.compare(password, user.password_hash);
    if (!valid) return NextResponse.json({ error: "Invalid credentials" }, { status: 401 });
    const token = crypto.randomUUID();
    return NextResponse.json({ success: true, token, email, userId: user.id });
  }

  return NextResponse.json({ error: "Unknown action" }, { status: 400 });
}
