/**
 * CRUD API Route for Todo
 * Auto-generated by Cozanet OS. Uses Supabase for persistence.
 */

import { NextRequest, NextResponse } from 'next/server';
export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

async function supabaseFetch(table: string, options: RequestInit = {}) {
  const resp = await fetch(`${SUPABASE_URL}/rest/v1/${table}`, {
    ...options,
    headers: { 'apikey': SUPABASE_KEY!, 'Authorization': `Bearer ${SUPABASE_KEY}`, 'Content-Type': 'application/json', ...options.headers },
  });
  return resp;
}

export async function GET(req: NextRequest) {
  const url = new URL(req.url);
  const id = url.searchParams.get("id");
  if (id) {
    const resp = await supabaseFetch('todo?id=eq.${id}&select=*');
    const data = await resp.json();
    if (!data.length) return NextResponse.json({ error: "Not found" }, { status: 404 });
    return NextResponse.json(data[0]);
  }
  const resp = await supabaseFetch('todo?select=*');
  const items = await resp.json();
  return NextResponse.json({ count: items.length, results: items });
}

export async function POST(req: NextRequest) {
  const body = await req.json();
  const resp = await supabaseFetch('todo', {
    method: 'POST',
    body: JSON.stringify({ ...body, created_at: new Date().toISOString() }),
    headers: { 'Prefer': 'return=representation' },
  });
  const created = await resp.json();
  return NextResponse.json(created[0] || created, { status: 201 });
}

export async function PUT(req: NextRequest) {
  const url = new URL(req.url);
  const id = url.searchParams.get("id");
  if (!id) return NextResponse.json({ error: "id required" }, { status: 400 });
  const body = await req.json();
  const resp = await supabaseFetch('todo?id=eq.${id}', {
    method: 'PATCH',
    body: JSON.stringify({ ...body, updated_at: new Date().toISOString() }),
    headers: { 'Prefer': 'return=representation' },
  });
  const updated = await resp.json();
  if (!updated.length) return NextResponse.json({ error: "Not found" }, { status: 404 });
  return NextResponse.json(updated[0]);
}

export async function DELETE(req: NextRequest) {
  const url = new URL(req.url);
  const id = url.searchParams.get("id");
  if (!id) return NextResponse.json({ error: "id required" }, { status: 400 });
  const resp = await supabaseFetch('todo?id=eq.${id}', {
    method: 'DELETE',
  });
  if (!resp.ok) return NextResponse.json({ error: "Delete failed" }, { status: 500 });
  return NextResponse.json({ success: true, id });
}
