/** Auth Middleware — Auto-generated by Cozanet OS */
import { NextRequest, NextResponse } from 'next/server';

// Public routes that dont require auth
const publicRoutes = ["/", "/login", "/register", "/api/auth", "/favicon.ico"];

export function middleware(req: NextRequest) {
  const path = req.nextUrl.pathname;
  if (publicRoutes.some((r) => path === r || path.startsWith(r + "/"))) {
    return NextResponse.next();
  }
  const token = req.headers.get("authorization")?.replace("Bearer ", "") || req.cookies.get("auth-token")?.value;
  if (!token) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  // TODO: Verify JWT token here
  return NextResponse.next();
}

export const config = {
  matcher: ['/((?!_next/static|_next/image|favicon.ico).*)'],
};
